### ISSUE TITLE
workflow: yadage hello.yaml doesn't validate

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-demo-helloworld#8]
`hello.yaml` is preventing helloworld example to be runable
```console
$ yadage-validate hello.yaml
ERROR:yadage.validator_workflow:validation error
Traceback (most recent call last):
  File "/Users/rodrigdi/.virtualenvs/yadage/lib/python2.7/site-packages/yadage/validator_workflow.py", line 36, in main
    workflow, toplevel=toplevel, schemadir=schemadir, validate=True)
  File "/Users/rodrigdi/.virtualenvs/yadage/lib/python2.7/site-packages/yadage/workflow_loader.py", line 5, in workflow
    data = yadageschemas.load(source, toplevel, schema_name, schemadir, validate)
  File "/Users/rodrigdi/.virtualenvs/yadage/lib/python2.7/site-packages/yadageschemas/__init__.py", line 172, in load
    validator(schema_name,schemadir).validate(data)
  File "/Users/rodrigdi/.virtualenvs/yadage/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: {'step': {'process': {'cmd': 'python helloworld.py --name "{name}" --sleeptimer {delay}', 'process_type': 'string-interpolated-cmd'}, 'publisher': {'publisher_type': 'frompar-pub'}, 'environment': {u'imagetag': u'latest', 'image': 'reanahub/reana-demo-helloworld', u'envscript': u'', 'environment_type': 'docker-encapsulated', u'env': {}, u'resources': []}}, 'scheduler_type': 'singlestep-stage', 'parameters': [{'value': {'output': 'delay', 'expression_type': 'stage-output-selector', 'stages': 'init', 'unwrap': True}, 'key': 'delay'}, {'value': {'output': 'name', 'expression_type': 'stage-output-selector', 'stages': 'init', 'unwrap': True}, 'key': 'name'}]} is not valid under any of the given schemas

Failed validating u'oneOf' in schema[u'properties'][u'stages'][u'items'][u'properties'][u'scheduler']:
    {u'oneOf': [{u'$ref': u'scheduler/singlestep-stage-schema.json#'},
                {u'$ref': u'scheduler/multistep-stage-schema.json#'}],
     u'type': u'object'}

On instance[u'stages'][0][u'scheduler']:
    {'parameters': [{'key': 'delay',
                     'value': {'expression_type': 'stage-output-selector',
                               'output': 'delay',
                               'stages': 'init',
                               'unwrap': True}},
                    {'key': 'name',
                     'value': {'expression_type': 'stage-output-selector',
                               'output': 'name',
                               'stages': 'init',
                               'unwrap': True}}],
     'scheduler_type': 'singlestep-stage',
     'step': {'environment': {u'env': {},
                              'environment_type': 'docker-encapsulated',
                              u'envscript': u'',
                              'image': 'reanahub/reana-demo-helloworld',
                              u'imagetag': u'latest',
                              u'resources': []},
              'process': {'cmd': 'python helloworld.py --name "{name}" --sleeptimer {delay}',
                          'process_type': 'string-interpolated-cmd'},
              'publisher': {'publisher_type': 'frompar-pub'}}}
workflow does not validate against schema
```

The error is not very clear though, since if add the following lines to `hello.yaml`  the spec gets validated:
```yaml
stages:
  - name: helloworld
    dependencies: [init]
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        name: {stages: init, output: name, unwrap: True}
        delay: {stages: init, output: delay, unwrap: True}
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'python helloworld.py --name "{name}" --sleeptimer {delay}'
        publisher:
          publisher_type: 'frompar-pub'
      >>> outputmap:
      >>>   output: '{workdir}/output/output.txt'
        environment:
          environment_type: 'docker-encapsulated'
          image: 'reanahub/reana-demo-helloworld'
```

```console
$ yadage-validate hello.yaml
workflow validates against schema
```

Since `helloworld.py` is writing to a file (see [here](https://github.com/reanahub/reana-demo-helloworld/blob/master/helloworld.py#L33)) we can use it as we are not providing it as a parameter for the workflow anymore.

P.S. We might want to add `yadage-validate`  to travis.
